name: Build Flutter APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        run: |
          git init
          git remote add origin https://github.com/aduganwabay-cpu/ai-chatbot.git
          git fetch origin main
          git checkout main

      - name: Install Java
        run: sudo apt-get update && sudo apt-get install -y openjdk-17-jdk

      - name: Install Flutter
        run: |
          git clone https://github.com/flutter/flutter.git -b stable --depth 1 _flutter
          echo "$GITHUB_WORKSPACE/_flutter/bin" >> $GITHUB_PATH

      - name: Get Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
